console.log("hola mundo")
console.log("Hello world")
console.log("Hallo Welt")
console.log("Γειά σου Κόσμε")
console.log("Salut monde")
console.log("Olá mundo")
console.log("Oláこんにちは世界")
console.log("Salut Lume")
console.log("Ciao mondo")
console.log("Hola món")
